WLA-595: Adds Discount to Order
Guestlogix/traveler-ios pull request #407
Opened 2020-03-26 12:04 UTC by josippetric

Needed to implement WLA-595
https://guestlogix.atlassian.net/browse/WLA-595

**Description**

**Issues that should be CLOSED by merge of this PR:**
* Fixes #

**Related issues that should be LINKED to this PR:**
* Connects #

2020-03-26 13:03 UTC, rhoque-glx approved these changes

2020-03-26 16:56 UTC, OmarPadierna requested changes

2020-03-26 16:56 UTC, OmarPadierna commented on traveler-swift-core/TravelerKit/Models/Discount.swift
> +public struct Discount: Decodable {
It should be named DiscountCoupon

2020-03-26 16:56 UTC, OmarPadierna commented on traveler-swift-core/TravelerKit/Models/Order.swift
> +    public let discount: Discount?
public let coupon: DiscountCoupon

2020-03-26 17:38 UTC, josippetric commented on traveler-swift-core/TravelerKit/Models/Discount.swift
> +public struct Discount: Decodable {
Done

2020-03-26 17:38 UTC, josippetric commented on traveler-swift-core/TravelerKit/Models/Order.swift
> +    public let discount: Discount?
Done

2020-03-26 19:21 UTC, josippetric commented
@OmarPadierna I've made the change. Discount is not DiscountCoupon.

2020-03-27 14:37 UTC, OmarPadierna approved these changes

2020-03-27 14:41 UTC, merged